imageSquaredDimension = 227
batchSize = 48
learningRate = 10**-1
baseFolder = '/home/filip/workbench/tree-images'
trainLmdbPath = baseFolder + '/workspace/lmdb/train-augmented-dataset-lmdb-{}'.format(imageSquaredDimension)
testLmdbPath = baseFolder + '/workspace/lmdb/test-augmented-dataset-lmdb-{}'.format(imageSquaredDimension)
valLmdbPath = baseFolder + '/workspace/lmdb/val-augmented-dataset-lmdb-{}'.format(imageSquaredDimension)
checkpointPath = baseFolder + '/checkpoints'
labelsPath = baseFolder + '/labels.json'
imageLabelMapPath = baseFolder + '/feature_labels.json'
trainImageLabelMapPath = baseFolder + '/feature_labels_train.json'
testImageLabelMapPath = baseFolder + '/feature_labels_test.json'
valImageLabelMapPath = baseFolder + '/feature_labels_val.json'
trainIters = 50
statisticsEvery = 5
workspaceRootFolder = baseFolder + '/workspace'
initNetPath = baseFolder + '/workspace/saves/init_net_{}.pb'.format(imageSquaredDimension)
predictNetPath = baseFolder + '/workspace/saves/predict_net_{}.pb'.format(imageSquaredDimension)
